// File: layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import './style/markdown.css'
import './style/prose.css'
import { Header } from './components/index'
import dynamic from 'next/dynamic';

// const ArtPlum = dynamic(() => import('./components/ArtPlum/ArtPlum'), { ssr: false });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // console.log(inter.className);
  
  return (
    <html lang="en" className="h-full">
      <body className={`shiki ${inter.className} flex flex-col h-full`}>
        <Header />
        <main className="grow h-0 p-4">
          {children}
        </main>
      </body>
    </html>
  );
}
